{
  "services": [
    {
      "type": "web",
      "name": "sistema-trolleo",
      "env": "node",
      "plan": "free",
      "buildCommand": "npm install",
      "startCommand": "npm start",
      "healthCheckPath": "/"
    }
  ]
}
